"""empty message

Revision ID: 27d1235963d8
Revises: 11a1352d9e59
Create Date: 2023-12-12 14:08:23.929777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27d1235963d8'
down_revision = '11a1352d9e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=False))
        batch_op.drop_column('departmen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departmen', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('department')

    # ### end Alembic commands ###
