"""store table

Revision ID: 53278b3e5e6d
Revises: 
Create Date: 2023-12-12 12:07:39.740527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53278b3e5e6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=54), nullable=False),
    sa.Column('address', sa.String(length=54), nullable=False),
    sa.Column('phone', sa.String(length=54), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store')
    # ### end Alembic commands ###
