"""empty message

Revision ID: 540a30c2b4ac
Revises: d5d41b29fb45
Create Date: 2023-12-18 23:06:08.143883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '540a30c2b4ac'
down_revision = 'd5d41b29fb45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('promotion_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_transactions_promotion_id'), ['promotion_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_promotion_id'))
        batch_op.alter_column('promotion_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###
