"""empty message

Revision ID: 8d286e5a0c04
Revises: 7baef4911574
Create Date: 2023-12-12 12:25:03.782682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d286e5a0c04'
down_revision = '7baef4911574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('full_date', sa.Date(), nullable=False),
    sa.Column('day_name', sa.String(length=9), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('day_of_year', sa.Integer(), nullable=False),
    sa.Column('month_name', sa.String(length=9), nullable=False),
    sa.Column('month_of_year', sa.Integer(), nullable=False),
    sa.Column('year_of_date', sa.Integer(), nullable=False),
    sa.Column('an_event', sa.Boolean(), nullable=False),
    sa.Column('event_name', sa.String(length=99), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_date'),
    sa.UniqueConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=54), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('init_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('stores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=54), nullable=False),
    sa.Column('address', sa.String(length=54), nullable=False),
    sa.Column('phone', sa.String(length=54), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('date_model', schema=None) as batch_op:
        batch_op.drop_index('full_date')
        batch_op.drop_index('id')

    op.drop_table('date_model')
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_index('id')

    op.drop_table('store')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index('id')

    op.drop_table('product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=54), nullable=False),
    sa.Column('qty', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('init_price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=False)

    op.create_table('store',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=54), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=54), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=54), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=False)

    op.create_table('date_model',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('full_date', sa.DATE(), nullable=False),
    sa.Column('day_name', mysql.VARCHAR(length=9), nullable=False),
    sa.Column('day_of_week', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('day_of_month', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('day_of_year', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('month_name', mysql.VARCHAR(length=9), nullable=False),
    sa.Column('month_of_year', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('year_of_date', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('an_event', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('event_name', mysql.VARCHAR(length=99), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('date_model', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=False)
        batch_op.create_index('full_date', ['full_date'], unique=False)

    op.drop_table('stores')
    op.drop_table('products')
    op.drop_table('dates')
    # ### end Alembic commands ###
