"""empty message

Revision ID: e263749a0bff
Revises: 8d286e5a0c04
Create Date: 2023-12-12 12:52:20.874571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e263749a0bff'
down_revision = '8d286e5a0c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('date_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['date_id'], ['dates.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_date_id'), ['date_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_store_id'), ['store_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_store_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_product_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_date_id'))

    op.drop_table('transactions')
    # ### end Alembic commands ###
